### ISSUE TITLE
JSON Decoding exception occurs when receiving 0 length streamed tweets

### ISSUE THREAD

**Issue by avi-c** [twitivity/twitter-stream.py#14]
I've been getting periodic crashes due to exceptions being raised on line 109 of `twitter_stream.py`

They happen intermittently and I realized they were occurring when a 0 length tweet would be streamed in.

I added a check for a non-zero length of `response_lines` before doing the `data = json.loads(response_lines)` line to skip those types of responses. This prevents the decode of the invalid response and avoids the crash.

I have a PR ready but can't push one to the repo.

**Comment by saadmanrafat** [comment]
We have this same issue reported #12 twice this week. I'm taking care of the issue. Please  [we revamping towards are new release.](twitivity.dev) Something must have went wrong with the settings.

**Comment by saadmanrafat** [comment]
This I just made created a pull request (not from my account) to test out the new changes in settings. This should resolve the issue. I'll wait for your feedback! Thank you for contributing.

**Comment by avi-c** [comment]
I'm still getting the error when I try this on the terminal command line:


```
->twitter-stream.py git:(avic/ignoreEmptyResponse) git push --set-upstream origin avic/ignoreEmptyResponse
ERROR: Permission to twitivity/twitter-stream.py.git denied to avi-c.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by saadmanrafat** [comment]
are you using [gh](https://cli.github.com/) CLI tool?

**Comment by avi-c** [comment]
No, I'm just using regular command line git which I use for contributing to both work repos (public & private) and my own projects.

**Comment by saadmanrafat** [comment]
> No, I'm just using regular command line git which I use for contributing to both work repos (public & private) and my own projects.

This is frustrating. I'll try to create the issue and update post an update.

**Comment by saadmanrafat** [comment]
I changed the branch `trunk` from `master` to `main` 

if you have a local branch, please make the following changes

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by avi-c** [comment]
I'm still getting the same problem even after switching to the `main` branch. Here is the output of `git remote show origin`:

➜  twitter-stream.py git:(avic/ignoreEmptyResponse) git remote show origin
* remote origin
  Fetch URL: git@github.com:twitivity/twitter-stream.py.git
  Push  URL: git@github.com:twitivity/twitter-stream.py.git
  HEAD branch: main
  Remote branches:
    main                       tracked
    refs/remotes/origin/master stale (use 'git remote prune' to remove)
  Local branch configured for 'git pull':
    main merges with remote main
  Local ref configured for 'git push':
    main pushes to main (local out of date)

**Comment by saadmanrafat** [comment]
> No, I'm just using regular command line git which I use for contributing to both work repos (public & private) and my own projects.

That other request, once approved, would solve the problem. I'm sure it will work out for both of us.

**Comment by saadmanrafat** [comment]
@avi-c  Some Branches are Projected [Read About Branch Protection Rules here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)

**Comment by saadmanrafat** [comment]
Default branch protection configurations are changed. Outside collaborators can easily create pull requests! Some protection measures are there to stay. Twitivity will guide how to create PR requests on organizations' repositories.
